// <auto-generated />
using System;
using Girlyf.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Girlyf.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Girlyf.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Line2")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Girlyf.API.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("MobileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Girlyf.API.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Girlyf.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Girlyf.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            ImageUrl = "/assets/images/categories/necklace.avif",
                            IsActive = true,
                            Name = "Necklace",
                            Slug = "necklace"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            ImageUrl = "/assets/images/categories/earring.avif",
                            IsActive = true,
                            Name = "Earring",
                            Slug = "earring"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            ImageUrl = "/assets/images/categories/bangle.avif",
                            IsActive = true,
                            Name = "Bangle",
                            Slug = "bangle"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            ImageUrl = "/assets/images/categories/ring.avif",
                            IsActive = true,
                            Name = "Ring",
                            Slug = "ring"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            ImageUrl = "/assets/images/categories/bracelet.avif",
                            IsActive = true,
                            Name = "Bracelet",
                            Slug = "bracelet"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            ImageUrl = "/assets/images/categories/pendant.avif",
                            IsActive = true,
                            Name = "Pendant",
                            Slug = "pendant"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            ImageUrl = "/assets/images/categories/chain.avif",
                            IsActive = true,
                            Name = "Chain",
                            Slug = "chain"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            ImageUrl = "/assets/images/categories/anklet.avif",
                            IsActive = true,
                            Name = "Anklet",
                            Slug = "anklet"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            ImageUrl = "/assets/images/categories/mangalsutra.avif",
                            IsActive = true,
                            Name = "Mangalsutra",
                            Slug = "mangalsutra"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            ImageUrl = "/assets/images/categories/nosepin.avif",
                            IsActive = true,
                            Name = "Nose Pin",
                            Slug = "nose-pin"
                        });
                });

            modelBuilder.Entity("Girlyf.API.Models.CmsSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkText")
                        .HasColumnType("text");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SectionKey")
                        .IsUnique();

                    b.ToTable("CmsSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            SectionKey = "hero_banner",
                            Title = "Hero Banner Carousel",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6540)
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            SectionKey = "category_grid",
                            Title = "Shop By Category",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6540)
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            SectionKey = "featured_products",
                            SubTitle = "Handpicked designs for every occasion",
                            Title = "Featured Collection",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6550)
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            SectionKey = "video_ad",
                            Title = "Product Customization",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6550)
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            SectionKey = "aira_collection",
                            SubTitle = "Lightweight everyday jewellery",
                            Title = "AIRA Collection",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6550)
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IsActive = true,
                            SectionKey = "shop_by_gender",
                            Title = "Shop For",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6550)
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IsActive = true,
                            SectionKey = "earring_styles",
                            SubTitle = "Find your perfect pair",
                            Title = "Earring Styles",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6550)
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IsActive = true,
                            SectionKey = "bestsellers",
                            SubTitle = "Most loved by our customers",
                            Title = "Best Sellers",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6560)
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IsActive = true,
                            SectionKey = "testimonials",
                            SubTitle = "Hear what our customers say",
                            Title = "Customer Stories",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6560)
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            IsActive = true,
                            SectionKey = "blog_preview",
                            SubTitle = "Jewellery tips, trends & more",
                            Title = "From Our Blog",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6560)
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            IsActive = true,
                            SectionKey = "store_locator",
                            SubTitle = "Come visit us in Bangalore",
                            Title = "Visit Our Store",
                            UpdatedAt = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6560)
                        });
                });

            modelBuilder.Entity("Girlyf.API.Models.CmsSectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CmsSectionId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExtraData")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("MobileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CmsSectionId");

                    b.ToTable("CmsSectionItems");
                });

            modelBuilder.Entity("Girlyf.API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Girlyf.API.Models.GoldRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Karat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatePerGram")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("GoldRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "All",
                            EffectiveDate = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6520),
                            Karat = "24K",
                            RatePerGram = 7200m
                        },
                        new
                        {
                            Id = 2,
                            City = "All",
                            EffectiveDate = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6530),
                            Karat = "22K",
                            RatePerGram = 6600m
                        },
                        new
                        {
                            Id = 3,
                            City = "All",
                            EffectiveDate = new DateTime(2026, 3, 29, 14, 59, 6, 970, DateTimeKind.Utc).AddTicks(6530),
                            Karat = "18K",
                            RatePerGram = 5400m
                        });
                });

            modelBuilder.Entity("Girlyf.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("text");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ShippingCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Girlyf.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GoldRateAtPurchase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Girlyf.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Collection")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<decimal>("GrossWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("boolean");

                    b.Property<string>("Karat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MakingChargePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Metal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NetWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Occasion")
                        .HasColumnType("text");

                    b.Property<string>("Purity")
                        .HasColumnType("text");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("StonePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("StoneWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WastagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Girlyf.API.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Girlyf.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Girlyf.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Girlyf.API.Models.StoreLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoreLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Round South, Thrissur, Kerala 680001",
                            City = "Thrissur",
                            DisplayOrder = 1,
                            IsActive = true,
                            Latitude = 10.5276,
                            Longitude = 76.214399999999998,
                            Name = "Girlyf Thrissur",
                            OpeningHours = "10:00 AM - 9:00 PM",
                            Phone = "+91-487-2420012",
                            State = "Kerala"
                        },
                        new
                        {
                            Id = 2,
                            Address = "MG Road, Ernakulam, Kerala 682011",
                            City = "Kochi",
                            DisplayOrder = 2,
                            IsActive = true,
                            Latitude = 9.9312000000000005,
                            Longitude = 76.267300000000006,
                            Name = "Girlyf Kochi",
                            OpeningHours = "10:00 AM - 9:00 PM",
                            Phone = "+91-484-2351234",
                            State = "Kerala"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Jayanagar 4th Block, Bangalore 560011",
                            City = "Bangalore",
                            DisplayOrder = 3,
                            IsActive = true,
                            Latitude = 12.927899999999999,
                            Longitude = 77.583100000000002,
                            Name = "Girlyf Bangalore",
                            OpeningHours = "10:00 AM - 9:00 PM",
                            Phone = "+91-80-26545678",
                            State = "Karnataka"
                        },
                        new
                        {
                            Id = 4,
                            Address = "T. Nagar, Chennai 600017",
                            City = "Chennai",
                            DisplayOrder = 4,
                            IsActive = true,
                            Latitude = 13.0418,
                            Longitude = 80.234099999999998,
                            Name = "Girlyf Chennai",
                            OpeningHours = "10:00 AM - 9:00 PM",
                            Phone = "+91-44-24345678",
                            State = "Tamil Nadu"
                        },
                        new
                        {
                            Id = 5,
                            Address = "RS Puram, Coimbatore 641002",
                            City = "Coimbatore",
                            DisplayOrder = 5,
                            IsActive = true,
                            Latitude = 11.0168,
                            Longitude = 76.955799999999996,
                            Name = "Girlyf Coimbatore",
                            OpeningHours = "10:00 AM - 9:00 PM",
                            Phone = "+91-422-2541234",
                            State = "Tamil Nadu"
                        });
                });

            modelBuilder.Entity("Girlyf.API.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerImage")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Absolutely stunning necklace! The craftsmanship is unmatched. Delivery was swift and secure.",
                            CustomerName = "Priya Sharma",
                            DisplayOrder = 1,
                            IsActive = true,
                            Location = "Bangalore",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Bought bangles for my wedding. Perfect weight and finish. The hallmark guarantee gives great confidence.",
                            CustomerName = "Anitha Menon",
                            DisplayOrder = 2,
                            IsActive = true,
                            Location = "Kochi",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Best online jewellery shopping experience. Live gold rates and transparent pricing — love it!",
                            CustomerName = "Lakshmi Narayanan",
                            DisplayOrder = 3,
                            IsActive = true,
                            Location = "Chennai",
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Ordered a pair of jhumkas. They look even better in person. Will definitely order again!",
                            CustomerName = "Deepa Raj",
                            DisplayOrder = 4,
                            IsActive = true,
                            Location = "Coimbatore",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("Girlyf.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Girlyf.API.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Girlyf.API.Models.Address", b =>
                {
                    b.HasOne("Girlyf.API.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Girlyf.API.Models.CartItem", b =>
                {
                    b.HasOne("Girlyf.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Girlyf.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Girlyf.API.Models.Category", b =>
                {
                    b.HasOne("Girlyf.API.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Girlyf.API.Models.CmsSectionItem", b =>
                {
                    b.HasOne("Girlyf.API.Models.CmsSection", "CmsSection")
                        .WithMany("Items")
                        .HasForeignKey("CmsSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmsSection");
                });

            modelBuilder.Entity("Girlyf.API.Models.Order", b =>
                {
                    b.HasOne("Girlyf.API.Models.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Girlyf.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Girlyf.API.Models.OrderItem", b =>
                {
                    b.HasOne("Girlyf.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Girlyf.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Girlyf.API.Models.Product", b =>
                {
                    b.HasOne("Girlyf.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Girlyf.API.Models.ProductImage", b =>
                {
                    b.HasOne("Girlyf.API.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Girlyf.API.Models.RefreshToken", b =>
                {
                    b.HasOne("Girlyf.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Girlyf.API.Models.Review", b =>
                {
                    b.HasOne("Girlyf.API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Girlyf.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Girlyf.API.Models.Wishlist", b =>
                {
                    b.HasOne("Girlyf.API.Models.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Girlyf.API.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Girlyf.API.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Girlyf.API.Models.CmsSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Girlyf.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Girlyf.API.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Girlyf.API.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
